### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by caramel2312** [OS-IS/ai201-shumejko#1]

**Comment by caramel2312** [comment]
![image](https://github.com/user-attachments/assets/3c08d375-b01f-42e4-a5c0-e4426fcd0e75)

**Comment by caramel2312** [comment]
![image](https://github.com/user-attachments/assets/6fa2f1e7-221b-489b-836f-4521b7cebf62)

**Comment by caramel2312** [comment]
![image](https://github.com/user-attachments/assets/63578569-cd2b-4d10-b78d-fd8adde38d3d)

**Comment by caramel2312** [comment]
![image](https://github.com/user-attachments/assets/8b1855d2-e7fa-4f85-b6bc-1a88e5005ed7)

**Comment by caramel2312** [comment]
![image](https://github.com/user-attachments/assets/a2035a05-5434-4382-9000-4aa50257aac1)

**Comment by caramel2312** [comment]
![image](https://github.com/user-attachments/assets/5b780ca8-bc09-45e3-a30e-1b24b21290fb)

**Comment by caramel2312** [comment]
![image](https://github.com/user-attachments/assets/2c4e4a58-23d6-44f6-93cc-30951bd6698d)

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 5 балів.
Дякую
