### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [OS-IS/ai201-shumejko#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
5) Відомо, що з серпня 2021 року GitHub-сервер пропонує PAT 
для процесу аутентифікації під час безпечного оновлення GitHub-репозиторію. 
Поясніть, будь ласка, чому так було зроблено?

**Comment by caramel2312** [comment]
Перехід на Personal Access Token (PAT) був необхідним для покращення безпеки та гнучкості управління доступом у GitHub по причинам: 
1. посилення безпеки (паролі можна було легко перехватити або просто підібрати, PAT дає в свою чергу унікальний токен, який дає доступ тільки до певних ресурсів, а також має свій срок дії);
2. багатофакторна аутентифікація (це дозволило використати двохфакторну аутентифікацію, в якій крім токена можна використати ще один механізм перевірки, наприклад одноразовий пароль OTP, що ускладнює доступ до облікового запису, навіть якщо токен потрапить до зловмисника);
3. гранульоване управління (токену можна задати до яких саме операцій він дозволяє доступ, наприклад тільки читання даних без прав на внесення змін);
4. універсальність (на відмінну від паролів, токени можуть надати гнучкість в управлінні доступом до репозиторіїв: їх можна використати для різних інтеграцій з зовнішніми сервісами та скриптами).

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
Дякую.
